---

- name: Run file commands
  hosts: all
  gather_facts: false

  tasks:
    - name: Create a directory
      file:
        path: /home/luisgr/myfolder
        state: directory
        owner: luisgr
        group: luisgr

    - name: touch sample-template.bak file
      file:
        path: /home/luisgr/sample-template.bak
        state: absent