---

- name: Basic playbook run ALL
  gather_facts: true 
  hosts: all
  tasks: 
    - name: Doing a ping
      ping:

    - name: Show info
      debug:
        msg: "Machine name: {{ ansible_hostname }}"
